{config, lib, pkgs, ...}:
let
  cfg = config.fndx.services.openssh;
in
with lib;
{
    options = {
        fndx.services.openssh = {
            enable = mkEnableOption "OpenSSH";
            PermitRootLogin = mkEnableOption "Root login for SSH";
            authorizedKeys = mkOption {

                example = ["ssh-ed25519 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA fndx@fndx"];
                type = types.listOf types.str;
                description = mdDoc "The ssh key used to authenticate to the foundxtion autogenerated user.";
            };
        };
    };

    config = mkIf cfg.enable {
        services.openssh = {
            enable = true;
            settings = {
                PasswordAuthentication = false;
                KbdInteractiveAuthentication = false;
                PermitRootLogin = mkMerge [
                  (mkIf cfg.PermitRootLogin "yes")
                  (mkIf (!cfg.PermitRootLogin) "no")
                ];
            };
        };
    };
}
