{ config, pkgs, ... }:
let
  secrets = import ../secrets.nix;
in
{
  users.users.fndx = {
    initialPassword = "foundxtion";
    isNormalUser = true;
    description = "Foundxtion autogenerated user";
    extraGroups = [ "wheel" "networkmanager" ];
    packages = with pkgs; [
      # TODO: add any binary needed for foundxtion
    ];
    openssh.authorizedKeys.keys = [
      secrets.authorizedKey
    ];
  };
}
