{ config, pkgs, ... }:
let
  secrets = import ../secrets.nix;
in
{
  users.users.foundation = {
    initialPassword = "foundation";
    isNormalUser = true;
    description = "Foundation autogenerated user";
    extraGroups = [ "wheel" "networkmanager" ];
    packages = with pkgs; [
      # TODO: add any binary needed for foundation
    ];
    openssh.authorizedKeys.keys = [
      secrets.authorizedKey
    ];
  };
}
