{ config, pkgs, ... }:
let
  secrets = import ../secrets.nix;
in
{
  users.users."${secrets.username}" = {
    initialHashedPassword = secrets.initialPasswordHash;
    isNormalUser = true;
    description = "Foundxtion autogenerated user";
    extraGroups = [ "wheel" "networkmanager" "docker" ];
    packages = with pkgs; [
      # TODO: add any binary needed for user
    ];
    openssh.authorizedKeys.keys = secrets.authorizedKeys;
  };
}
